export type marriageDataType = {
    id: string,
    fullName: string,
    nationalID: string,
    date: string,
    address: string,
    phoneNumber: string,
    familyName: string,
    jop: string,
    monthlyIncome: string,
    anotherSource: string,
    total: string,
    wifeName: string,
    wifeNationalID: string,
    numberChildren: string,
    agriculturalHolding: boolean,
    landArea: string | null,
    landCultivation: boolean,
    areaCultivation: string | null,
    landDescription: string,
    houseDescription: string,
    requiredNeeds: string,
    estimatedBudget: {
        item: string,
        number: number,
        unitPrice: number,
        total: number,
    }[],
    researcherOpinion: string,
    researcher: string,
    serveiceType: "illness" | "marriage",
}
export type illnessDataType = {
    id: string,
    fullName: string,
    nationalID: string,
    date: string,
    address: string,
    phoneNumber: string,
    familyName: string,
    jop: string,
    monthlyIncome: string,
    anotherSource: string,
    total: string,
    wifeName: string,
    wifeNationalID: string,
    numberChildren: string,
    caseData: string,
    houseDescription: string,
    requiredNeeds: string,
    estimatedBudget: {
        item: string,
        number: number,
        unitPrice: number,
        total: number,
    }[],
    researcherOpinion: string,
    researcher: string,
    serveiceType: "illness" | "marriage",
}