export type ServiceDataType = {
    QuadNameProvided: string,
    NationalNumberProvided: string,
    SubmissionDate: string,
    AdressProvided: string,
    phoneNumberProvided: string,
    BreadwinnerNameProvided: string,
    WorkProvided: string,
    MonthlyIncome: number,
    OtherSources: number,
    TotalIncome: number,
    husbandFamily: string,
    NationalNumberFamily: string,
    NumberOfChildren: number,
    DoesHeOwnAgriculturalProperty: boolean,
    IsAnyLandBeingCultivated: boolean,
    DescriptionOfAgriculturalLandInCaseOfCultivation: string,
    descHouse: string,
    Requirements: string | null,
    ResearcherSaw: string,
    Researcher: string,
    Status: "الزواج" | "المرض",
    Items: {
        item: string,
        number: number,
        PriceItem: number,
        Total: number,
    }[],
    landArea: string | null,
    areaCultivation: string | null,
    caseData: string | null,
}